name: biogas_monitor
description: Biogas monitoring app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_database: ^10.5.0
  http: ^1.2.0
  fl_chart: ^0.66.0

flutter:
  uses-material-design: true
